### ISSUE TITLE
pdf objects list

### ISSUE THREAD

**Issue by michieldeclerck** [libis/ca_crkc_17#11]
@naeemmuhammad 
same issues as #10 

- empty pages in between
- images that are spread over several pages
- if possible they want the new style of the database reflected in the lay-out

![image](https://user-images.githubusercontent.com/41673932/45141607-9febe000-b1b6-11e8-9c3b-21d19daadb79.png)

**Comment by naeemmuhammad** [comment]
@michieldeclerck can you write object number of this object?

**Comment by michieldeclerck** [comment]
CRKC.0198.0024

**Comment by naeemmuhammad** [comment]
Large images that appear on multiple pages have been restricted to maximum one page by putting a limit on their height (in this case is 600 pixels).  When restriction applied such images are cut (towards height), therefore complete images are not shown.
