### ISSUE TITLE
inspector in object editor/objectfiche

### ISSUE THREAD

**Issue by michieldeclerck** [libis/ca_crkc_17#4]
@naeemmuhammad 

In the inspector nothing happens when you click 'show media'. See if it is possible to activate function 'show/hide media'.

CRKC does not use the functions 'wijzig type' and 'kopieer object'. They would like them removed if possible.

![inspector](https://user-images.githubusercontent.com/41673932/44786439-6ef72400-ab94-11e8-8e37-8f0541ab35e0.jpg)

**Comment by naeemmuhammad** [comment]
@roxannewyns  'wijzig type' and 'kopieer object' options are not available to less privileged user roles/groups. Administrators will always have these options, it is possible to remove them at all by tempering the source code. However all changes in the code will have to be inherited and manually adapted in all future upgrades, therefore i would avoid disabling them.

show media fix: b935bd7045662edc2a969c4f14bb594e6229c051
